export const leadStages = [
  "New",
  "Contacted",
  "Qualified",
  "Proposal",
  "Won",
  "Lost",
];

export const dealStages = [
  "New",
  "Qualified",
  "Proposal",
  "Negotiation",
  "Won",
  "Lost",
];
export const money = (value) =>
  `₹${Number(value || 0).toLocaleString("en-IN")}`;

export const initialLeads = [
  {
    id: 1,
    name: "Arun Kumar",
    company: "Vertex Labs",
    email: "arun@vertexlabs.com",
    phone: "+91 98765 43210",
    source: "Website",
    stage: "Qualified",
    value: 18500,
    followUp: "2026-09-24",
    owner: "Eswar",
    notes: "Interested in the annual CRM plan.",
    created: "2026-09-08",
  },
  {
    id: 2,
    name: "Priya Sharma",
    company: "Northstar Studio",
    email: "priya@northstar.io",
    phone: "+91 98410 22771",
    source: "Referral",
    stage: "Proposal",
    value: 32000,
    followUp: "2026-09-23",
    owner: "Eswar",
    notes: "Proposal shared. Waiting for procurement feedback.",
    created: "2026-09-06",
  },
  {
    id: 3,
    name: "Karthik Raj",
    company: "BluePeak Media",
    email: "karthik@bluepeak.in",
    phone: "+91 90030 11882",
    source: "LinkedIn",
    stage: "Contacted",
    value: 12500,
    followUp: "2026-09-27",
    owner: "Meena",
    notes: "Requested a product walkthrough.",
    created: "2026-09-10",
  },
  {
    id: 4,
    name: "Divya Menon",
    company: "Aster Retail",
    email: "divya@asterretail.com",
    phone: "+91 99520 66431",
    source: "Campaign",
    stage: "New",
    value: 8900,
    followUp: "2026-09-29",
    owner: "Rahul",
    notes: "New inbound lead.",
    created: "2026-09-12",
  },
  {
    id: 5,
    name: "Vignesh S",
    company: "Orbit Systems",
    email: "vignesh@orbitsystems.in",
    phone: "+91 97908 33145",
    source: "Website",
    stage: "Won",
    value: 45000,
    followUp: "2026-10-04",
    owner: "Eswar",
    notes: "Renewal opportunity for next quarter.",
    created: "2026-09-02",
  },
  {
    id: 6,
    name: "Nithya Rao",
    company: "Greenline Foods",
    email: "nithya@greenlinefoods.com",
    phone: "+91 97891 77810",
    source: "Event",
    stage: "Lost",
    value: 15000,
    followUp: "2026-09-20",
    owner: "Meena",
    notes: "Budget postponed.",
    created: "2026-08-29",
  },
  {
    id: 7,
    name: "Sanjay Kumar",
    company: "Elevate Finance",
    email: "sanjay@elevatefin.com",
    phone: "+91 98842 77110",
    source: "Referral",
    stage: "Qualified",
    value: 27500,
    followUp: "2026-09-25",
    owner: "Rahul",
    notes: "Strong fit for analytics module.",
    created: "2026-09-07",
  },
  {
    id: 8,
    name: "Aishwarya P",
    company: "PixelCraft",
    email: "aishwarya@pixelcraft.in",
    phone: "+91 99622 11420",
    source: "Instagram",
    stage: "Contacted",
    value: 9800,
    followUp: "2026-09-30",
    owner: "Eswar",
    notes: "Asked for pricing options.",
    created: "2026-09-13",
  },
];

export const initialContacts = [
  {
    id: 1,
    name: "Arun Kumar",
    company: "Vertex Labs",
    email: "arun@vertexlabs.com",
    phone: "+91 98765 43210",
    role: "Founder",
    status: "Active",
    lastContact: "2026-09-19",
  },
  {
    id: 2,
    name: "Priya Sharma",
    company: "Northstar Studio",
    email: "priya@northstar.io",
    phone: "+91 98410 22771",
    role: "Operations Head",
    status: "Active",
    lastContact: "2026-09-18",
  },
  {
    id: 3,
    name: "Karthik Raj",
    company: "BluePeak Media",
    email: "karthik@bluepeak.in",
    phone: "+91 90030 11882",
    role: "Marketing Lead",
    status: "Active",
    lastContact: "2026-09-17",
  },
  {
    id: 4,
    name: "Divya Menon",
    company: "Aster Retail",
    email: "divya@asterretail.com",
    phone: "+91 99520 66431",
    role: "Purchase Manager",
    status: "New",
    lastContact: "2026-09-14",
  },
  {
    id: 5,
    name: "Vignesh S",
    company: "Orbit Systems",
    email: "vignesh@orbitsystems.in",
    phone: "+91 97908 33145",
    role: "CTO",
    status: "Active",
    lastContact: "2026-09-20",
  },
];

export const initialDeals = [
  {
    id: 1,
    title: "Vertex Labs — Annual CRM",
    company: "Vertex Labs",
    contact: "Arun Kumar",
    value: 18500,
    stage: "Qualified",
    probability: 55,
    closeDate: "2026-10-08",
    owner: "Eswar",
  },
  {
    id: 2,
    title: "Northstar — Growth Plan",
    company: "Northstar Studio",
    contact: "Priya Sharma",
    value: 32000,
    stage: "Proposal",
    probability: 70,
    closeDate: "2026-10-03",
    owner: "Eswar",
  },
  {
    id: 3,
    title: "BluePeak — Team License",
    company: "BluePeak Media",
    contact: "Karthik Raj",
    value: 12500,
    stage: "New",
    probability: 20,
    closeDate: "2026-10-15",
    owner: "Meena",
  },
  {
    id: 4,
    title: "Aster Retail — Starter",
    company: "Aster Retail",
    contact: "Divya Menon",
    value: 8900,
    stage: "Negotiation",
    probability: 82,
    closeDate: "2026-09-30",
    owner: "Rahul",
  },
  {
    id: 5,
    title: "Orbit — Enterprise",
    company: "Orbit Systems",
    contact: "Vignesh S",
    value: 45000,
    stage: "Won",
    probability: 100,
    closeDate: "2026-09-21",
    owner: "Eswar",
  },
  {
    id: 6,
    title: "Elevate — Analytics",
    company: "Elevate Finance",
    contact: "Sanjay Kumar",
    value: 27500,
    stage: "Proposal",
    probability: 68,
    closeDate: "2026-10-12",
    owner: "Rahul",
  },
];

export const activities = [
  {
    id: 1,
    type: "call",
    title: "Discovery call completed",
    text: "Discussed workflow automation and CRM adoption.",
    person: "Arun Kumar",
    date: "Today · 10:30 AM",
  },
  {
    id: 2,
    type: "mail",
    title: "Proposal emailed",
    text: "Growth plan proposal sent to Priya Sharma.",
    person: "Priya Sharma",
    date: "Yesterday · 4:15 PM",
  },
  {
    id: 3,
    type: "meeting",
    title: "Product demo scheduled",
    text: "Demo booked for the BluePeak team.",
    person: "Karthik Raj",
    date: "Sep 19 · 2:00 PM",
  },
  {
    id: 4,
    type: "note",
    title: "New note added",
    text: "Budget approval expected before month end.",
    person: "Divya Menon",
    date: "Sep 18 · 11:20 AM",
  },
];

export const revenueData = [
  { month: "Apr", revenue: 42000, target: 50000 },
  { month: "May", revenue: 51000, target: 54000 },
  { month: "Jun", revenue: 48000, target: 56000 },
  { month: "Jul", revenue: 69000, target: 62000 },
  { month: "Aug", revenue: 76000, target: 70000 },
  { month: "Sep", revenue: 84000, target: 78000 },
];

export const sourceData = [
  { name: "Website", value: 34 },
  { name: "Referral", value: 25 },
  { name: "Campaign", value: 18 },
  { name: "LinkedIn", value: 13 },
  { name: "Events", value: 10 },
];
